config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :documents
  root 'documents#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
    validates :name, presence: true, length: {minimum: 4 }
    validates :text, presence: true, length: {minimum: 1 }
    validates :description, presence: true, length: {maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :home, :show]

  def new
    @document = Document.new()
  end

  def create
    document = Document.new(document_params)
    if document.save
      redirect_to documents_path
    else
      redirect_to new_document_path
    end
  end

  def index
    @documents = Document.all()
  end

  def show
    @document = Document.find(params[:id])
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    document = Document.find(params[:id])
    if document.update(document_params)
      redirect_to documents_path
    else
      redirect_to edit_document_path(document)
    end
  end

  def destroy
    document = Document.find(params[:id])
    document.destroy
    redirect_to documents_path
  end

  def home
    @documents = Document.all
  end
  
private
  def document_params
    params.require(:document).permit(:name, :text, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/edit.html.erb
<h2>Edit Document "<strong class="name"><%= @document.name %></strong>"</h2>

<%= form_for @document do |f|%>
    Name: <%= f.text_field :name %> </br>
    <%= f.text_field :description, size: "63", value: "Description...(maximum 30 symbols)" %> </br>
    <%= f.text_area :text, size: "60x12" %></br>
    <%= f.submit "Save Changes" %>
<% end  %>

<%= link_to "Cancel", document_path(@document)%>

app/views/documents/home.html.erb
<h1>HOME</h1>
<%= link_to "Create new", new_document_path%> </br>
<%= link_to "All documents", documents_path %>
</br>

 <% @documents.last(3).each do |document| %>
        <p class="name">
            <%= document.name %> -> <%= document.description %>
            <%= link_to "View", document_path(document) %>
        </p>
        </br>
<% end %>

app/views/documents/index.html.erb
<h1>All documents</h1>

<%= link_to "Create new", new_document_path%></br>
<%= link_to "Home", root_path %>

</br>

<% @documents.each do |document| %>

    <p class="name"><%= document.name %>    
    <%= link_to "View", document_path(document) %>
    </p>

<% end %>   

app/views/documents/new.html.erb
<h2><strong>Create new Document!</strong> </br></h2>

<%= form_for @document, url: {action: "create"} do |f|%>

    <div class="field">
        Name: <%= f.text_field :name %> </br></br>   
        <%= f.text_field :description, size: "63", value: "Description...(Maximum 30 symbols)" %> </br>
        <%= f.text_area :text, size: "60x12" %>
    </div>

    <div class="actions">
    <%= f.submit "Create" %>
    </div>
<% end %>

<%= link_to "Cancel", documents_path%>

app/views/documents/show.html.erb
<h2>Document "<strong class="name"><%= @document.name %></strong>"</h2>

<% if params[:user] != nil && params[:pass] != nil %>
    <% access  = false %>
    <%u = User.where(email: params[:user]).take %>
    <% if u != nil %>
        <% if u.valid_password?(params[:pass])  %>
            <% access = true %>
        <% end %>
    <% end %>

    <% if access %>
        <div class = "notice"> Access Granted! </div> 
    <% else %>
        <div class = "alert"> Access Denied! </div> 
    <% end %>
    
    
<% else %>
    
    <div class="document_description"><%= @document.description %></div>
    <div class="document_content"><%= @document.text %></div>

    <div>
        <%= link_to "Edit", edit_document_path(@document) %> </br>
        <%= link_to "Back to all documents", documents_path %> </br>
        <%= link_to "Delete", document_path(@document), method: :delete, data: {confirm: "Do you really wish to destroy that document?"}%>
    </div>    

<% end %>

app/views/layouts/_navbar.html.erb
<nav>
    
    <% if user_signed_in? %>
      Logged in as <strong class="name"><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path  %> |
      <%= link_to "Login", new_user_session_path  %>
    <% end %> 
    | <%= link_to "Home", root_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A18MartinPenev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %><div class="notice"> <%= notice %> </div><% end %>
    <% if alert %><div class="alert"> <%= alert %> </div><% end %>
    
    <%= render partial: "layouts/navbar" %>

    <%= yield %>
  </body>
</html>